### ISSUE TITLE
Delete the temporary txt.gz file?

### ISSUE THREAD

**Issue by mstrimas** [cboettig/birddb#3]
I know the untared txt.gz file is put in the temp directory so will be deleted automatically. Wondering if there's any benefit to manually deleting it via `unlink()` immediately after import to parquet since it is such a massive file? Seems like it could be the friendly thing to do to avoid users seeing their HD space decrease by 100+ GB.

**Comment by cboettig** [comment]
Yeah, makes sense to me. Should be purged when R session restarts, but it's true some users manage not to do so very often and can occasionally see issues.  I see no harm in deleting more aggressively.   want to send a lil PR for this one?
